from ...i18n import TEXT

EXTRA = {
    'browser_setup': ['Browser setup', 'Настройка браузеров', 'Nastavení prohlížečů', 'Brauzerlarni sozlash'],
    'browser_not_installed': ['Not detected', 'Не обнаружен', 'Nenalezen', 'Topilmadi'],
    'browser_not_found': ['This browser was not found. Install it through your approved company process.', 'Браузер не найден. Установите его разрешённым в компании способом.', 'Prohlížeč nebyl nalezen. Nainstalujte jej postupem schváleným společností.', "Brauzer topilmadi. Uni kompaniya tasdiqlagan usulda o'rnating."],
    'browser_manual_setup': ['Manual setup', 'Ручная настройка', 'Ruční nastavení', "Qo'lda sozlash"],
    'browser_verify_host': ['Connection verification required', 'Нужна проверка подключения', 'Vyžaduje ověření připojení', 'Ulanishni tekshirish kerak'],
    'firefox_pending': ['Pending signed XPI', 'Ожидается подписанный XPI', 'Čeká na podepsaný XPI', 'Imzolangan XPI kutilmoqda'],
    'browser_copy_address': ['Copy extensions address', 'Скопировать адрес расширений', 'Kopírovat adresu rozšíření', 'Kengaytmalar manzilini nusxalash'],
    'browser_paste_address': ['Paste into the address bar in {browser} and press Enter.', 'Вставьте в адресную строку {browser} и нажмите Enter.', 'Vložte do adresního řádku prohlížeče {browser} a stiskněte Enter.', '{browser} manzil satriga joylashtiring va Enter tugmasini bosing.'],
    'browser_address_copied': ['Copied {address}. Paste it into the address bar in {browser} and press Enter.', 'Скопировано: {address}. Вставьте в адресную строку {browser} и нажмите Enter.', 'Zkopírováno: {address}. Vložte adresu do adresního řádku prohlížeče {browser} a stiskněte Enter.', '{address} nusxalandi. Uni {browser} manzil satriga joylashtiring va Enter tugmasini bosing.'],
    'browser_copy_failed': ['Could not copy the browser address. Try again.', 'Не удалось скопировать адрес браузера. Повторите попытку.', 'Adresu prohlížeče se nepodařilo zkopírovat. Zkuste to znovu.', "Brauzer manzilini nusxalab bo'lmadi. Qayta urinib ko'ring."],
    'switch_employee': ['Change employee', 'Сменить сотрудника', 'Změnit zaměstnance', 'Xodimni almashtirish'],
    'switch_notice': ["Enter the next employee's code from the same company. Pending events remain assigned to the previous employee. Current browser extensions are required.", 'Введите код следующего сотрудника той же компании. Ожидающие события останутся за прежним сотрудником. Нужны актуальные расширения браузера.', 'Zadejte kód dalšího zaměstnance stejné společnosti. Čekající události zůstanou přiřazené předchozímu zaměstnanci. Jsou vyžadována aktuální rozšíření prohlížečů.', "Shu kompaniyadagi keyingi xodim kodini kiriting. Kutilayotgan hodisalar oldingi xodimga tegishli bo'lib qoladi. Brauzer kengaytmalari joriy versiyada bo'lishi kerak."],
    'employee_changed': ['Employee changed', 'Сотрудник изменён', 'Zaměstnanec změněn', 'Xodim almashtirildi'],
    'employee_switch_not_ready': ['Update and reconnect your work browser extensions before changing employee, then try again.', 'Обновите и подключите расширения рабочих браузеров перед сменой сотрудника, затем повторите.', 'Před změnou zaměstnance aktualizujte a znovu připojte rozšíření pracovních prohlížečů a zkuste to znovu.', "Xodimni almashtirishdan oldin ish brauzeri kengaytmalarini yangilang va qayta ulang, so'ng yana urining."],
    'employee_switch_pending_activity': ['Current activity could not be saved yet. The employee was not changed. Check disk space and try again.', 'Текущая активность ещё не сохранена. Сотрудник не изменён. Проверьте место на диске и повторите.', 'Aktuální aktivitu se zatím nepodařilo uložit. Zaměstnanec nebyl změněn. Zkontrolujte místo na disku a zkuste to znovu.', "Joriy faoliyat hali saqlanmadi. Xodim almashtirilmadi. Diskdagi joyni tekshiring va qayta urining."],
    'employee_switch_conflict': ['The active employee changed during this request. Check the displayed employee and try again.', 'Во время запроса активный сотрудник изменился. Проверьте имя на экране и повторите.', 'Během požadavku se aktivní zaměstnanec změnil. Zkontrolujte zobrazené jméno a zkuste to znovu.', "So'rov davomida faol xodim o'zgardi. Ekrandagi ismni tekshiring va qayta urining."],
    'employee_company_mismatch': ['Use an employee code from this company.', 'Используйте код сотрудника этой компании.', 'Použijte kód zaměstnance této společnosti.', 'Shu kompaniya xodimining kodidan foydalaning.'],
    'cancel_action': ['Cancel', 'Отмена', 'Zrušit', 'Bekor qilish'],
    'administration': ['Application', 'Приложение', 'Aplikace', 'Ilova'],
    'per_user_notice': ['Installed for this OS account.', 'Установлено для этой учётной записи ОС.', 'Nainstalováno pro tento účet OS.', "Ushbu OT hisobi uchun o'rnatilgan."],
    'user_autostart': ['Start at user sign-in', 'Запуск при входе пользователя', 'Spuštění při přihlášení uživatele', 'Foydalanuvchi kirganda ishga tushish'],
    'autostart_registered': ['Registered; OS launch not verified', 'Зарегистрирован; запуск ОС не проверен', 'Zaregistrováno; spuštění OS neověřeno', "Ro'yxatga olingan; OT ishga tushirishi tekshirilmagan"],
    'autostart_missing': ['Not registered', 'Не зарегистрирован', 'Nezaregistrováno', "Ro'yxatga olinmagan"],
    'status_unknown': ['Not verified', 'Не проверено', 'Neověřeno', 'Tekshirilmagan'],
    'stop_agent': ['Stop agent', 'Остановить агент', 'Zastavit agenta', "Agentni to'xtatish"],
    'stop_title': ['Stop SOFT Tracking?', 'Остановить SOFT Tracking?', 'Zastavit SOFT Tracking?', "SOFT Tracking to'xtatilsinmi?"],
    'stop_confirm': ['Stop now', 'Остановить сейчас', 'Zastavit nyní', "Hozir to'xtatish"],
    'stop_notice': ['The app will close and stop collecting activity until you launch it again or next sign in. Pending activity will be saved and sent after the next launch.', 'Приложение закроется и прекратит сбор активности до следующего запуска или входа в систему. Неотправленная активность сохранится и будет отправлена после следующего запуска.', 'Aplikace se zavře a přestane sbírat aktivitu do dalšího spuštění nebo přihlášení. Neodeslaná aktivita se uloží a odešle po příštím spuštění.', "Ilova yopiladi va uni qayta ishga tushirguningizcha yoki tizimga keyingi kirishingizgacha faoliyatni yig'maydi. Yuborilmagan faoliyat saqlanadi va keyingi ishga tushirishdan so'ng yuboriladi."],
    'stop_authorized': ['Stopping and saving pending activity', 'Остановка и сохранение ожидающей активности', 'Zastavování a ukládání čekající aktivity', "To'xtatilmoqda va kutilayotgan faoliyat saqlanmoqda"],
    'stop_pending_activity': ['Current activity could not be saved. The app remains open. Check disk space and try again.', 'Не удалось сохранить текущую активность. Приложение остаётся открытым. Проверьте место на диске и повторите.', 'Aktuální aktivitu se nepodařilo uložit. Aplikace zůstává otevřená. Zkontrolujte místo na disku a zkuste to znovu.', "Joriy faoliyat saqlanmadi. Ilova ochiq qoladi. Diskdagi joyni tekshiring va qayta urining."],
    'stop_cancelled': ['The app was not stopped. Collection continues.', 'Приложение не остановлено. Сбор продолжается.', 'Aplikace nebyla zastavena. Sběr pokračuje.', "Ilova to'xtatilmadi. Yig'ish davom etadi."],
    'stop_busy': ['Another operation is in progress. Wait for it to finish and try again.', 'Выполняется другая операция. Дождитесь её завершения и повторите.', 'Probíhá jiná operace. Počkejte na její dokončení a zkuste to znovu.', "Boshqa amal bajarilmoqda. U tugashini kuting va qayta urinib ko'ring."],
    'stop_error': ['Could not stop the app. It remains open. Try again.', 'Не удалось остановить приложение. Оно остаётся открытым. Повторите попытку.', 'Aplikaci se nepodařilo zastavit. Zůstává otevřená. Zkuste to znovu.', "Ilovani to'xtatib bo'lmadi. U ochiq qoladi. Qayta urinib ko'ring."],
    'uninstall_agent': ['Remove app', 'Удалить приложение', 'Odinstalovat aplikaci', "Ilovani o'chirish"],
    'uninstall_opening': ['Opening the uninstaller...', 'Открываем программу удаления...', 'Otevírání odinstalačního programu...', "O'chirish dasturi ochilmoqda..."],
    'uninstall_started': ['The uninstaller is open. Confirm or cancel removal in its window.', 'Программа удаления открыта. Подтвердите или отмените удаление в её окне.', 'Odinstalační program je otevřený. Potvrďte nebo zrušte odebrání v jeho okně.', "O'chirish dasturi ochiq. Uning oynasida o'chirishni tasdiqlang yoki bekor qiling."],
    'uninstall_requested': ['Removal requested. Follow the uninstaller window for the result.', 'Удаление запрошено. Результат появится в окне программы удаления.', 'Odinstalace byla vyžádána. Výsledek sledujte v okně odinstalačního programu.', "O'chirish so'raldi. Natijani o'chirish dasturi oynasida kuzating."],
    'uninstall_cancelled': ['Removal was cancelled. The app is still installed.', 'Удаление отменено. Приложение осталось установленным.', 'Odinstalace byla zrušena. Aplikace zůstává nainstalovaná.', "O'chirish bekor qilindi. Ilova o'rnatilgan holda qoldi."],
    'uninstall_failed': ['Removal could not be completed. Try again.', 'Не удалось завершить удаление. Повторите попытку.', 'Odinstalaci se nepodařilo dokončit. Zkuste to znovu.', "O'chirishni yakunlab bo'lmadi. Qayta urinib ko'ring."],
    'uninstall_unavailable': ['The uninstaller is unavailable for this installation. The app has not been removed.', 'Программа удаления недоступна для этой установки. Приложение не удалено.', 'Odinstalační program pro tuto instalaci není dostupný. Aplikace nebyla odebrána.', "Bu o'rnatish uchun o'chirish dasturi mavjud emas. Ilova o'chirilmadi."],
    'uninstall_busy': ['Another operation is in progress. Wait for it to finish and try again.', 'Выполняется другая операция. Дождитесь её завершения и повторите.', 'Probíhá jiná operace. Počkejte na její dokončení a zkuste to znovu.', "Boshqa amal bajarilmoqda. U tugashini kuting va qayta urinib ko'ring."],
    'guide_unavailable': ['The installation guide is missing from this application package. Contact your administrator.', 'В пакете приложения отсутствует инструкция. Обратитесь к администратору.', 'V balíčku aplikace chybí návod. Obraťte se na správce.', "Ilova paketida qo'llanma yo'q. Administratorga murojaat qiling."],
    'connect': ['Connect', 'Подключить', 'Připojit', 'Ulash'],
    'company': ['Company', 'Компания', 'Společnost', 'Kompaniya'],
    'employee': ['Employee', 'Сотрудник', 'Zaměstnanec', 'Xodim'],
    'browser': ['Browser', 'Браузер', 'Prohlížeč', 'Brauzer'],
    'settings': ['Settings', 'Настройки', 'Nastavení', 'Sozlamalar'],
    'receiving': ['Data delivery', 'Получение данных', 'Doručení dat', 'Maʼlumotlarni yetkazish'],
    'check_again': ['Check again', 'Проверить снова', 'Ověřit znovu', 'Qayta tekshirish'],
    'received': ['Session received by server', 'Сессия получена сервером', 'Relace doručena serveru', 'Seans serverga yetkazildi'],
    'waiting_session': ['Waiting for a website session', 'Ожидаем сессию с сайта', 'Čekání na relaci webu', 'Sayt seansi kutilmoqda'],
    'last_session': ['Last confirmed session', 'Последняя подтверждённая сессия', 'Poslední potvrzená relace', 'Oxirgi tasdiqlangan seans'],
    'last_confirmation': ['Server confirmation', 'Подтверждение сервера', 'Potvrzení serveru', 'Server tasdigʻi'],
    'no_confirmation': ['No sessions received yet', 'Сессии ещё не получены', 'Zatím nebyly přijaty žádné relace', 'Seanslar hali olinmagan'],
    'auto_update': ['Automatic updates', 'Автообновление', 'Automatické aktualizace', 'Avtomatik yangilash'],
    'check_updates': ['Check for updates', 'Проверить обновления', 'Vyhledat aktualizace', 'Yangilanishlarni tekshirish'],
    'update_last_checked': ['Last checked', 'Последняя проверка', 'Poslední kontrola', 'Oxirgi tekshiruv'],
    'update_request_failed': ['Could not request an update check. Try again.', 'Не удалось запросить проверку обновлений. Повторите попытку.', 'Kontrolu aktualizací se nepodařilo vyžádat. Zkuste to znovu.', "Yangilanish tekshiruvini so'rab bo'lmadi. Qayta urinib ko'ring."],
    'help': ['Help', 'Помощь', 'Nápověda', 'Yordam'],
    'details': ['Connection details', 'Подробнее о соединении', 'Podrobnosti připojení', 'Ulanish tafsilotlari'],
    'company_installer': ['Company installer', 'Компания из установщика', 'Instalátor společnosti', 'Kompaniya oʻrnatuvchisi'],
    'checking': ['Checking...', 'Проверяем...', 'Ověřování...', 'Tekshirilmoqda...'],
    'not_connected': ['Not connected', 'Не подключено', 'Nepřipojeno', 'Ulanmagan'],
    'last_contact': ['Last connection', 'Последнее подключение', 'Poslední spojení', 'Oxirgi ulanish'],
    'await_browser': ['Waiting for extension', 'Ожидаем расширение', 'Čekání na rozšíření', 'Kengaytma kutilmoqda'],
    'company_rules': ['Company settings', 'Настройки компании', 'Nastavení společnosti', 'Kompaniya sozlamalari'],
    'on': ['Enabled', 'Включено', 'Zapnuto', 'Yoqilgan'],
    'off': ['Disabled', 'Выключено', 'Vypnuto', 'Oʻchirilgan'],
    'web_time': ['Website activity', 'Время на сайтах', 'Aktivita na webech', 'Saytlardagi faollik'],
    'clicks': ['Clicks and forms', 'Клики и формы', 'Kliknutí a formuláře', 'Bosishlar va shakllar'],
    'fields': ['Field values', 'Значения полей', 'Hodnoty polí', 'Maydon qiymatlari'],
    'programs': ['Application inventory', 'Список программ', 'Seznam aplikací', 'Dasturlar roʻyxati'],
    'allowed_sites': ['Allowed websites', 'Разрешённые сайты', 'Povolené weby', 'Ruxsat etilgan saytlar'],
    'no_sites': ['No websites enabled', 'Нет разрешённых сайтов', 'Žádné povolené weby', 'Ruxsat etilgan saytlar yoʻq'],
    'saved_local': ['Waiting to send', 'Ожидают отправки', 'Čeká na odeslání', 'Yuborish kutilmoqda'],
    'needs_attention': ['Needs attention', 'Требует внимания', 'Vyžaduje pozornost', 'Eʼtibor talab etiladi'],
    'seconds': ['s', 'с', 's', 's'],
    'check_complete': ['Connection checked', 'Подключение проверено', 'Připojení ověřeno', 'Ulanish tekshirildi'],
    'connecting': ['Connecting...', 'Подключаем...', 'Připojování...', 'Ulanmoqda...'],
    'company_disabled': ['Time tracking is disabled in company settings', 'Учёт времени выключен в настройках компании', 'Sledování času je vypnuté v nastavení společnosti', 'Vaqt hisobi kompaniya sozlamalarida oʻchirilgan'],
    'employee_disabled': ['Time tracking is disabled for this employee', 'Учёт времени выключен для сотрудника', 'Sledování času je pro zaměstnance vypnuté', 'Xodim uchun vaqt hisobi oʻchirilgan'],
}


def messages(language):
    language = language if language in ('en', 'ru', 'cs', 'uz') else 'en'
    index = ('en', 'ru', 'cs', 'uz').index(language)
    return dict(TEXT[language], **{key: values[index] for key, values in EXTRA.items()})
