from ...i18n import TEXT

EXTRA = {
    'browser_setup': ['Browser setup', 'Настройка браузеров', 'Nastavení prohlížečů', 'Brauzerlarni sozlash'],
    'browser_not_installed': ['Not detected', 'Не обнаружен', 'Nenalezen', 'Topilmadi'],
    'browser_not_found': ['This browser was not found. Install it through your approved company process.', 'Браузер не найден. Установите его разрешённым в компании способом.', 'Prohlížeč nebyl nalezen. Nainstalujte jej postupem schváleným společností.', "Brauzer topilmadi. Uni kompaniya tasdiqlagan usulda o'rnating."],
    'browser_manual_setup': ['Manual setup', 'Ручная настройка', 'Ruční nastavení', "Qo'lda sozlash"],
    'browser_verify_host': ['Connection verification required', 'Нужна проверка подключения', 'Vyžaduje ověření připojení', 'Ulanishni tekshirish kerak'],
    'firefox_pending': ['Pending signed XPI', 'Ожидается подписанный XPI', 'Čeká na podepsaný XPI', 'Imzolangan XPI kutilmoqda'],
    'browser_page_opened': ['Browser extensions page opened', 'Открыта страница расширений браузера', 'Stránka rozšíření prohlížeče otevřena', 'Brauzer kengaytmalari sahifasi ochildi'],
    'browser_open_failed': ['Could not open this browser. Check that it is installed.', 'Не удалось открыть браузер. Проверьте, что он установлен.', 'Prohlížeč nelze otevřít. Ověřte, že je nainstalovaný.', "Brauzer ochilmadi. O'rnatilganini tekshiring."],
    'switch_employee': ['Change employee', 'Сменить сотрудника', 'Změnit zaměstnance', 'Xodimni almashtirish'],
    'switch_notice': ["Enter the next employee's code from the same company. Pending events remain assigned to the previous employee. Current browser extensions are required.", 'Введите код следующего сотрудника той же компании. Ожидающие события останутся за прежним сотрудником. Нужны актуальные расширения браузера.', 'Zadejte kód dalšího zaměstnance stejné společnosti. Čekající události zůstanou přiřazené předchozímu zaměstnanci. Jsou vyžadována aktuální rozšíření prohlížečů.', "Shu kompaniyadagi keyingi xodim kodini kiriting. Kutilayotgan hodisalar oldingi xodimga tegishli bo'lib qoladi. Brauzer kengaytmalari joriy versiyada bo'lishi kerak."],
    'employee_changed': ['Employee changed', 'Сотрудник изменён', 'Zaměstnanec změněn', 'Xodim almashtirildi'],
    'employee_switch_not_ready': ['Update and reconnect your work browser extensions before changing employee, then try again.', 'Обновите и подключите расширения рабочих браузеров перед сменой сотрудника, затем повторите.', 'Před změnou zaměstnance aktualizujte a znovu připojte rozšíření pracovních prohlížečů a zkuste to znovu.', "Xodimni almashtirishdan oldin ish brauzeri kengaytmalarini yangilang va qayta ulang, so'ng yana urining."],
    'employee_switch_pending_activity': ['Current activity could not be saved yet. The employee was not changed. Check disk space and try again.', 'Текущая активность ещё не сохранена. Сотрудник не изменён. Проверьте место на диске и повторите.', 'Aktuální aktivitu se zatím nepodařilo uložit. Zaměstnanec nebyl změněn. Zkontrolujte místo na disku a zkuste to znovu.', "Joriy faoliyat hali saqlanmadi. Xodim almashtirilmadi. Diskdagi joyni tekshiring va qayta urining."],
    'employee_switch_conflict': ['The active employee changed during this request. Check the displayed employee and try again.', 'Во время запроса активный сотрудник изменился. Проверьте имя на экране и повторите.', 'Během požadavku se aktivní zaměstnanec změnil. Zkontrolujte zobrazené jméno a zkuste to znovu.', "So'rov davomida faol xodim o'zgardi. Ekrandagi ismni tekshiring va qayta urining."],
    'employee_company_mismatch': ['Use an employee code from this company.', 'Используйте код сотрудника этой компании.', 'Použijte kód zaměstnance této společnosti.', 'Shu kompaniya xodimining kodidan foydalaning.'],
    'cancel_action': ['Cancel', 'Отмена', 'Zrušit', 'Bekor qilish'],
    'administration': ['Administration', 'Администрирование', 'Správa', 'Boshqaruv'],
    'per_user_notice': ['Installed for this OS account. Stopping through the app requires administrator approval. This is not a protected system service; the same OS user can still force-quit it.', 'Установлено для этой учётной записи ОС. Остановка через приложение требует подтверждения администратора. Это не защищённая системная служба: тот же пользователь ОС может принудительно завершить процесс.', 'Nainstalováno pro tento účet OS. Zastavení přes aplikaci vyžaduje schválení správce. Nejde o chráněnou systémovou službu; stejný uživatel OS ji stále může vynuceně ukončit.', "Ushbu OT hisobi uchun o'rnatilgan. Ilova orqali to'xtatish administrator tasdig'ini talab qiladi. Bu himoyalangan tizim xizmati emas; shu OT foydalanuvchisi jarayonni majburan yopishi mumkin."],
    'user_autostart': ['Start at user sign-in', 'Запуск при входе пользователя', 'Spuštění při přihlášení uživatele', 'Foydalanuvchi kirganda ishga tushish'],
    'autostart_registered': ['Registered; OS launch not verified', 'Зарегистрирован; запуск ОС не проверен', 'Zaregistrováno; spuštění OS neověřeno', "Ro'yxatga olingan; OT ishga tushirishi tekshirilmagan"],
    'autostart_missing': ['Not registered', 'Не зарегистрирован', 'Nezaregistrováno', "Ro'yxatga olinmagan"],
    'status_unknown': ['Not verified', 'Не проверено', 'Neověřeno', 'Tekshirilmagan'],
    'stop_agent': ['Stop with administrator approval', 'Остановить с подтверждением администратора', 'Zastavit se schválením správce', "Administrator tasdig'i bilan to'xtatish"],
    'stop_authorized': ['Stopping and saving pending activity', 'Остановка и сохранение ожидающей активности', 'Zastavování a ukládání čekající aktivity', "To'xtatilmoqda va kutilayotgan faoliyat saqlanmoqda"],
    'stop_pending_activity': ['Current activity could not be saved. The app remains open. Check disk space and try again.', 'Не удалось сохранить текущую активность. Приложение остаётся открытым. Проверьте место на диске и повторите.', 'Aktuální aktivitu se nepodařilo uložit. Aplikace zůstává otevřená. Zkontrolujte místo na disku a zkuste to znovu.', "Joriy faoliyat saqlanmadi. Ilova ochiq qoladi. Diskdagi joyni tekshiring va qayta urining."],
    'stop_cancelled': ['Administrator approval was cancelled. Collection continues.', 'Подтверждение администратора отменено. Сбор продолжается.', 'Schválení správce bylo zrušeno. Sběr pokračuje.', "Administrator tasdig'i bekor qilindi. Yig'ish davom etadi."],
    'stop_denied': ['Administrator approval was denied. Collection continues.', 'Администратор не разрешил остановку. Сбор продолжается.', 'Správce zastavení neschválil. Sběr pokračuje.', "Administrator to'xtatishga ruxsat bermadi. Yig'ish davom etadi."],
    'stop_timed_out': ['Administrator approval timed out. Collection continues.', 'Время ожидания подтверждения истекло. Сбор продолжается.', 'Vypršel čas pro schválení správcem. Sběr pokračuje.', "Administrator tasdig'ini kutish vaqti tugadi. Yig'ish davom etadi."],
    'stop_unavailable': ['Administrator approval is unavailable on this system. Collection continues.', 'Подтверждение администратора недоступно в этой системе. Сбор продолжается.', 'Schválení správce není v tomto systému dostupné. Sběr pokračuje.', "Bu tizimda administrator tasdig'i mavjud emas. Yig'ish davom etadi."],
    'stop_busy': ['Another approval request is in progress. Collection continues.', 'Уже выполняется другой запрос подтверждения. Сбор продолжается.', 'Probíhá jiný požadavek na schválení. Sběr pokračuje.', "Boshqa tasdiqlash so'rovi bajarilmoqda. Yig'ish davom etadi."],
    'stop_error': ['Administrator approval could not be verified. Collection continues.', 'Не удалось проверить подтверждение администратора. Сбор продолжается.', 'Schválení správce se nepodařilo ověřit. Sběr pokračuje.', "Administrator tasdig'ini tekshirib bo'lmadi. Yig'ish davom etadi."],
    'guide_unavailable': ['The installation guide is missing from this application package. Contact your administrator.', 'В пакете приложения отсутствует инструкция. Обратитесь к администратору.', 'V balíčku aplikace chybí návod. Obraťte se na správce.', "Ilova paketida qo'llanma yo'q. Administratorga murojaat qiling."],
    'connect': ['Connect', 'Подключить', 'Připojit', 'Ulash'],
    'company': ['Company', 'Компания', 'Společnost', 'Kompaniya'],
    'employee': ['Employee', 'Сотрудник', 'Zaměstnanec', 'Xodim'],
    'browser': ['Browser', 'Браузер', 'Prohlížeč', 'Brauzer'],
    'settings': ['Settings', 'Настройки', 'Nastavení', 'Sozlamalar'],
    'receiving': ['Data delivery', 'Получение данных', 'Doručení dat', 'Maʼlumotlarni yetkazish'],
    'check_again': ['Check again', 'Проверить снова', 'Ověřit znovu', 'Qayta tekshirish'],
    'open_dashboard': ['Open dashboard', 'Открыть дашборд', 'Otevřít přehled', 'Panelni ochish'],
    'received': ['Session received by server', 'Сессия получена сервером', 'Relace doručena serveru', 'Seans serverga yetkazildi'],
    'waiting_session': ['Waiting for a website session', 'Ожидаем сессию с сайта', 'Čekání na relaci webu', 'Sayt seansi kutilmoqda'],
    'last_session': ['Last confirmed session', 'Последняя подтверждённая сессия', 'Poslední potvrzená relace', 'Oxirgi tasdiqlangan seans'],
    'last_confirmation': ['Server confirmation', 'Подтверждение сервера', 'Potvrzení serveru', 'Server tasdigʻi'],
    'no_confirmation': ['No sessions received yet', 'Сессии ещё не получены', 'Zatím nebyly přijaty žádné relace', 'Seanslar hali olinmagan'],
    'auto_update': ['Automatic updates', 'Автообновление', 'Automatické aktualizace', 'Avtomatik yangilash'],
    'help': ['Help', 'Помощь', 'Nápověda', 'Yordam'],
    'details': ['Connection details', 'Подробнее о соединении', 'Podrobnosti připojení', 'Ulanish tafsilotlari'],
    'company_installer': ['Company installer', 'Компания из установщика', 'Instalátor společnosti', 'Kompaniya oʻrnatuvchisi'],
    'checking': ['Checking...', 'Проверяем...', 'Ověřování...', 'Tekshirilmoqda...'],
    'not_connected': ['Not connected', 'Не подключено', 'Nepřipojeno', 'Ulanmagan'],
    'last_contact': ['Last connection', 'Последнее подключение', 'Poslední spojení', 'Oxirgi ulanish'],
    'await_browser': ['Waiting for extension', 'Ожидаем расширение', 'Čekání na rozšíření', 'Kengaytma kutilmoqda'],
    'company_rules': ['Company settings', 'Настройки компании', 'Nastavení společnosti', 'Kompaniya sozlamalari'],
    'on': ['Enabled', 'Включено', 'Zapnuto', 'Yoqilgan'],
    'off': ['Disabled', 'Выключено', 'Vypnuto', 'Oʻchirilgan'],
    'web_time': ['Website activity', 'Время на сайтах', 'Aktivita na webech', 'Saytlardagi faollik'],
    'clicks': ['Clicks and forms', 'Клики и формы', 'Kliknutí a formuláře', 'Bosishlar va shakllar'],
    'fields': ['Field values', 'Значения полей', 'Hodnoty polí', 'Maydon qiymatlari'],
    'programs': ['Application inventory', 'Список программ', 'Seznam aplikací', 'Dasturlar roʻyxati'],
    'allowed_sites': ['Allowed websites', 'Разрешённые сайты', 'Povolené weby', 'Ruxsat etilgan saytlar'],
    'no_sites': ['No websites enabled', 'Нет разрешённых сайтов', 'Žádné povolené weby', 'Ruxsat etilgan saytlar yoʻq'],
    'saved_local': ['Waiting to send', 'Ожидают отправки', 'Čeká na odeslání', 'Yuborish kutilmoqda'],
    'needs_attention': ['Needs attention', 'Требует внимания', 'Vyžaduje pozornost', 'Eʼtibor talab etiladi'],
    'seconds': ['s', 'с', 's', 's'],
    'check_complete': ['Connection checked', 'Подключение проверено', 'Připojení ověřeno', 'Ulanish tekshirildi'],
    'connecting': ['Connecting...', 'Подключаем...', 'Připojování...', 'Ulanmoqda...'],
    'company_disabled': ['Time tracking is disabled in company settings', 'Учёт времени выключен в настройках компании', 'Sledování času je vypnuté v nastavení společnosti', 'Vaqt hisobi kompaniya sozlamalarida oʻchirilgan'],
    'employee_disabled': ['Time tracking is disabled for this employee', 'Учёт времени выключен для сотрудника', 'Sledování času je pro zaměstnance vypnuté', 'Xodim uchun vaqt hisobi oʻchirilgan'],
}


def messages(language):
    language = language if language in ('en', 'ru', 'cs', 'uz') else 'en'
    index = ('en', 'ru', 'cs', 'uz').index(language)
    return dict(TEXT[language], **{key: values[index] for key, values in EXTRA.items()})
